Test
sagarkv2020/demo pull request #1
Opened 2020-06-05 12:18 UTC by Rajesh-Puri

Creating Demo Pull request.

2020-06-06 02:45 UTC, sagarkv2020 requested changes

2020-06-06 02:45 UTC, sagarkv2020 commented on src/main/java/com/example/demo/controller/DemoController.java
> +	private class Hello {
Controller class should only have the API mapping . Model classes should be separately placed in the model package .

2020-06-10 03:28 UTC, sagarkv2020 requested changes
There is conflicts in this Pull Request.. Could you please check that ?

2020-06-10 04:16 UTC, Rajesh-Puri commented
Closing the pull request, not required.

2020-06-10 04:16 UTC, closed without merging